[package]
name = "skillchain-contracts"
version = "0.1.0"
edition = "2021"

[dependencies]
cosmwasm-std = "1.5.0"       
cw-storage-plus = "1.1.0"
schemars = "0.8"
serde = { version = "1.0", features = ["derive"] }
